baseURL = "https://cloudnativos.es/"
languageCode = "en-gb"
title = "Cloud Native Days Spain 2025"

# Theme
theme = "devfest-theme-hugo"

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

[params]
    title = "#3 Virtual Kubernetes Community Days"
    date = "October 28th and 29th, 2025"
    description = "Forma parte de la primera comunidad de hispanohablantes de Kubernetes. Descubre un evento de tres días en español lleno de experiencias, empresas emergentes y personas a las que les gusta tanto la tecnología como a ti."
    images = ["/images/featured/cloudnativos-featured-01.png"]
    email = " hello@cloudnativos.es"
    keywords = "event, cloudnative, spain, kubernetes, google, cloud"
    copyright = "Organized with ❤️  by Cloud Nativos Spain."
    cfpUrl = "https://go.cloudnativos.es/cfp" # TODO
    joinURL = "https://community.cncf.io/events/details/cloudnativos-spain-presents-cloudnativos-spain-2025/" # TODO
    appleTouchIcon = "/apple-icon.png"
    favicon32 = "/images/logos/favicon-32x32.ico"
    favicon16 = "/images/logos/favicon-16x16.ico"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#0000ff"

[params.logos]
    jumbo = "/images/logos/cloudnativos-logo-white.png"
    header = "/images/logos/cloudnativos-logo-comp.png"
    footer = "/images/logos/cloudnativos-logo-white.png"

[menu]
[[menu.main]]
    identifier = "schedule"
    name = "menu_main_schedule"
    url = "https://agenda.cloudnativos.es/" # TODO
    weight = 200
    external = true
# [[menu.main]]
#     identifier = "cfp"
#     name = "CFP"
#     url = "https://go.cloudnativos.es/cfp" # TODO
#     weight = 190
#     external = true

[languages]
[languages.en]
    weight = 1
    languageName = "gb"
    languageCode = "en"

[languages.es]
    weight = 2
    languageName = "es"
    languageCode = "es"

[languages.es.params]
    description = "Forma parte de la primera comunidad de hispanohablantes de Kubernetes. Descubre un evento de tres días en español lleno de experiencias, empresas emergentes y personas a las que les gusta tanto"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

